'use strict';

/* jshint ignore:start */
/**
 * This code was generated by
 * \ / _    _  _|   _  _
 *  | (_)\/(_)(_|\/| |(/_  v1.0.0
 *       /       /
 */
/* jshint ignore:end */

var _ = require('lodash');  /* jshint ignore:line */
var ServiceList = require('./proxy/service').ServiceList;
var Version = require('../../base/Version');  /* jshint ignore:line */


/* jshint ignore:start */
/**
 * Initialize the Proxy version of Preview
 *
 * @constructor Twilio.Preview.Proxy
 *
 * @property {Twilio.Preview.Proxy.ServiceList} services - services resource
 *
 * @param {Twilio.Preview} domain - The twilio domain
 */
/* jshint ignore:end */
class Proxy {
  constructor(public domain) {
  Version.prototype.constructor.call(this, domain, 'Proxy');

  // Resources
  this._services = undefined;
}

class Proxy extends Version {


Object.defineProperty(Proxy.prototype,
  'services', {
  get: function() {
    this._services = this._services || new ServiceList(this);
    return this._services;
  }
});

}

export = Proxy;
