'use strict';

/* jshint ignore:start */
/**
 * This code was generated by
 * \ / _    _  _|   _  _
 *  | (_)\/(_)(_|\/| |(/_  v1.0.0
 *       /       /
 */
/* jshint ignore:end */

import _ = require('lodash');  /* jshint ignore:line */
import Holodeck = require('../../../../../holodeck');  /* jshint ignore:line */
import Request = require(
    '../../../../../../../lib/http/request');  /* jshint ignore:line */
import Response = require(
    '../../../../../../../lib/http/response');  /* jshint ignore:line */
import RestException = require(
    '../../../../../../../lib/base/RestException');  /* jshint ignore:line */
import Twilio = require('../../../../../../../lib');  /* jshint ignore:line */
import serialize = require(
    '../../../../../../../lib/base/serialize');  /* jshint ignore:line */


var client;
var holodeck;

describe('StreamMessage', function() {
  beforeEach(function() {
    holodeck = new Holodeck();
    client = new Twilio('ACaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', 'AUTHTOKEN', {
      httpClient: holodeck
    });
  });
  it('should generate valid create request',
    function() {
      holodeck.mock(new Response(500, '{}'));

      var opts = {data: '{}'};
      var promise = client.sync.v1.services('ISaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa')
                                  .syncStreams('TOaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa')
                                  .streamMessages.create(opts);
      promise = promise.then(function() {
        throw new Error('failed');
      }, function(error) {
        expect(error.constructor).toBe(RestException.prototype.constructor);
      });
      promise.done();

      var solution = {
        serviceSid: 'ISaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
        streamSid: 'TOaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'
      };
      var url = _.template('https://sync.twilio.com/v1/Services/<%= serviceSid %>/Streams/<%= streamSid %>/Messages')(solution);

      var values = {Data: serialize.object('{}'), };
      holodeck.assertHasRequest(new Request({
          method: 'POST',
          url: url,
          data: values
      }));
    }
  );
  it('should generate valid create response',
    function() {
      var body = JSON.stringify({
          'sid': 'TZaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
          'data': {}
      });

      holodeck.mock(new Response(201, body));

      var opts = {data: '{}'};
      var promise = client.sync.v1.services('ISaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa')
                                  .syncStreams('TOaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa')
                                  .streamMessages.create(opts);
      promise = promise.then(function(response) {
        expect(response).toBeDefined();
      }, function() {
        throw new Error('failed');
      });

      promise.done();
    }
  );
});

