'use strict';

/* jshint ignore:start */
/**
 * This code was generated by
 * \ / _    _  _|   _  _
 *  | (_)\/(_)(_|\/| |(/_  v1.0.0
 *       /       /
 */
/* jshint ignore:end */

import _ = require('lodash');  /* jshint ignore:line */
import Domain = require('../base/Domain');  /* jshint ignore:line */
import V1 = require('./trunking/V1');  /* jshint ignore:line */


/* jshint ignore:start */
/**
 * Initialize trunking domain
 *
 * @constructor Twilio.Trunking
 *
 * @property {Twilio.Trunking.V1} v1 - v1 version
 * @property {Twilio.Trunking.V1.TrunkList} trunks - trunks resource
 *
 * @param {Twilio} twilio - The twilio client
 */
/* jshint ignore:end */
class Trunking {
  constructor(public twilio) {
  super(twilio, 'https://trunking.twilio.com');

  // Versions
  this._v1 = undefined;
}

class Trunking extends Domain {


Object.defineProperty(Trunking.prototype,
  'v1', {
  get: function() {
    this._v1 = this._v1 || new V1(this);
    return this._v1;
  }
});

Object.defineProperty(Trunking.prototype,
  'trunks', {
  get: function() {
    return this.v1.trunks;
  }
});

}

export = Trunking;
