'use strict';

/* jshint ignore:start */
/**
 * This code was generated by
 * \ / _    _  _|   _  _
 *  | (_)\/(_)(_|\/| |(/_  v1.0.0
 *       /       /
 */
/* jshint ignore:end */

import _ = require('lodash');  /* jshint ignore:line */
import Holodeck = require('../../../holodeck');  /* jshint ignore:line */
import Request = require(
    '../../../../../lib/http/request');  /* jshint ignore:line */
import Response = require(
    '../../../../../lib/http/response');  /* jshint ignore:line */
import RestException = require(
    '../../../../../lib/base/RestException');  /* jshint ignore:line */
import Twilio = require('../../../../../lib');  /* jshint ignore:line */


var client;
var holodeck;

describe('Export', function() {
  beforeEach(function() {
    holodeck = new Holodeck();
    client = new Twilio('ACaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', 'AUTHTOKEN', {
      httpClient: holodeck
    });
  });
  it('should generate valid fetch request',
    function() {
      holodeck.mock(new Response(500, '{}'));

      var promise = client.preview.bulk_exports.exports('resourceType').fetch();
      promise = promise.then(function() {
        throw new Error('failed');
      }, function(error) {
        expect(error.constructor).toBe(RestException.prototype.constructor);
      });
      promise.done();

      var solution = {resourceType: 'resourceType'};
      var url = _.template('https://preview.twilio.com/BulkExports/Exports/<%= resourceType %>')(solution);

      holodeck.assertHasRequest(new Request({
        method: 'GET',
        url: url
      }));
    }
  );
  it('should generate valid fetch response',
    function() {
      var body = JSON.stringify({
          'resource_type': 'Calls',
          'url': 'https://preview.twilio.com/BulkExports/Exports/Calls',
          'links': {
              'days': 'https://preview.twilio.com/BulkExports/Exports/Calls/Days'
          }
      });

      holodeck.mock(new Response(200, body));

      var promise = client.preview.bulk_exports.exports('resourceType').fetch();
      promise = promise.then(function(response) {
        expect(response).toBeDefined();
      }, function() {
        throw new Error('failed');
      });

      promise.done();
    }
  );
});

