'use strict';

/* jshint ignore:start */
/**
 * This code was generated by
 * \ / _    _  _|   _  _
 *  | (_)\/(_)(_|\/| |(/_  v1.0.0
 *       /       /
 */
/* jshint ignore:end */

var _ = require('lodash');  /* jshint ignore:line */
var CountryList = require('./messaging/country').CountryList;
var Page = require('../../../base/Page');  /* jshint ignore:line */

var MessagingList;
var MessagingPage;
var MessagingInstance;

/* jshint ignore:start */
/**
 * @constructor Twilio.Pricing.V1.MessagingList
 * @description Initialize the MessagingList
 *
 * @param {Twilio.Pricing.V1} version - Version of the resource
 */
/* jshint ignore:end */
MessagingList = class MessagingList {
  constructor(public version) {
  /* jshint ignore:start */
  /**
   * @function messaging
   * @memberof Twilio.Pricing.V1
   * @instance
   *
   * @param {string} sid - sid of instance
   *
   * @returns {Twilio.Pricing.V1.MessagingContext}
   */
  /* jshint ignore:end */
  class MessagingListInstance {
  constructor(public sid) {
    return MessagingListInstance.get(sid);
  }

  static _version = version;
  // Path Solution
  static _solution = {};

  // Components
  static _countries = undefined;

  Object.defineProperty(MessagingListInstance,
    'countries', {
    get: function countries() {
      if (!this._countries) {
        this._countries = new CountryList(this._version);
      }

      return this._countries;
    }
  });

  return MessagingListInstance;
};


/* jshint ignore:start */
/**
 * @constructor Twilio.Pricing.V1.MessagingPage
 * @augments Page
 * @description Initialize the MessagingPage
 *
 * @param {Twilio.Pricing.V1} version - Version of the resource
 * @param {object} response - Response from the API
 * @param {object} solution - Path solution
 *
 * @returns MessagingPage
 */
/* jshint ignore:end */
MessagingPage = class MessagingPage {
  constructor(public version, public response, public solution) {
  // Path Solution
  this._solution = solution;

  Page.prototype.constructor.call(this, version, response, this._solution);
};

class MessagingPage extends Page {


/* jshint ignore:start */
/**
 * Build an instance of MessagingInstance
 *
 * @function getInstance
 * @memberof Twilio.Pricing.V1.MessagingPage
 * @instance
 *
 * @param {object} payload - Payload response from the API
 *
 * @returns MessagingInstance
 */
/* jshint ignore:end */
getInstance(payload) {
  return new MessagingInstance(this._version, payload);
};


/* jshint ignore:start */
/**
 * @constructor Twilio.Pricing.V1.MessagingInstance
 * @description Initialize the MessagingContext
 *
 * @property {string} name - The name
 * @property {string} url - The url
 * @property {string} links - The links
 *
 * @param {Twilio.Pricing.V1} version - Version of the resource
 * @param {object} payload - The instance payload
 */
/* jshint ignore:end */
MessagingInstance = class MessagingInstance {
  constructor(public version, public payload) {
  this._version = version;

  // Marshaled Properties
  this.name = payload.name; // jshint ignore:line
  this.url = payload.url; // jshint ignore:line
  this.links = payload.links; // jshint ignore:line

  // Context
  this._context = undefined;
  this._solution = {};
};

export = {
  MessagingList: MessagingList,
  MessagingPage: MessagingPage,
  MessagingInstance: MessagingInstance
};
